image:
  - Visual Studio 2022
# FIXME: At some point we want to test our builds on Ubuntu?
#  - Ubuntu

version: 4.0.0.{build}

clone_depth: 1 # we only care about the commit we are building

nuget:
  project_feed: true

artifacts:
  - path: bin/nuget/*.nupkg
    name: OpenTK Nuget Packages

init:
  - git config --global core.autocrlf input

configuration: Release

build_script:
  - ps: ./build.ps1 -t RunCITests
