image:
  - Visual Studio 2019
  - Ubuntu

version: 4.0.0.{build}

artifacts:
  - path: bin/nuget/*.nupkg
    name: OpenTK Nuget Packages

init:
  - git config --global core.autocrlf input

configuration: Release

build_script:
  - ps: ./build.ps1 -t RunCITests
